In [4]:
keys = [1,2,9,4,5]
for i in keys:
    i +=1
    print(i)

2
3
10
5
6


In [1]:
import numpy as np
from scipy.sparse import csr_matrix

# 创建一个稀疏矩阵
row = np.array([0, 1, 2, 3])
col = np.array([0, 1, 2, 3])
data = np.array([1, 2, 3, 4])
sparse_matrix = csr_matrix((data, (row, col)), shape=(4, 4))

# 将稀疏矩阵转换为密集矩阵
dense_matrix = sparse_matrix.todense()

print(dense_matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [4]:
import numpy as np

# 假设有一个评分矩阵 R
R = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4],
])

# 参数初始化
num_users, num_items = R.shape
k = 2  # 特征的数量
U = np.random.rand(num_users, k)
print(U)
V = np.random.rand(num_items, k)
learning_rate = 0.01
iterations = 100
lambda_reg = 0.02  # 正则化项

# 训练模型
for epoch in range(iterations):
    for i in range(num_users):
        for j in range(num_items):
            if R[i, j] > 0:
                # 计算误差
                eij = R[i, j] - np.dot(U[i, :], V[j, :].T)
                # 更新U和V
                #print("V[j, :]",V[j, :],"U[i, :]",U[i, :])
                U[i, :] = U[i, :] + learning_rate * (eij * V[j, :] - lambda_reg * U[i, :])
                V[j, :] = V[j, :] + learning_rate * (eij * U[i, :] - lambda_reg * V[j, :])

# 预测评分矩阵
R_pred = U.dot(V.T)
print(R_pred)


[[0.52931253 0.94985403]
 [0.18190142 0.72101798]
 [0.35246824 0.3247706 ]
 [0.0595062  0.13120677]
 [0.48921533 0.75413871]]
[[4.95252097 1.87585966 4.08893049 1.43935175]
 [3.89476306 1.45408964 3.12460181 0.98190612]
 [1.09057764 1.04391707 3.6184253  4.79728097]
 [1.13048636 0.92870655 3.08985417 3.88327933]
 [3.97804978 1.87909852 4.88862345 3.80054299]]
